services:
  server:
    build: ./server
    ports:
      - "8000:8000"
  
    command: 
      python3 manage.py runserver 0.0.0.0:8000
    image: christiancagnazzo/sw2demoproject:server

  client:
    build: ./client
    image: christiancagnazzo/sw2demoproject:client
    ports:
      - "3000:3000"
    command: 
      npm start
      #npm i react-native-slide-charts --legacy-peer-deps \
      
