# Generated by Django 4.1.2 on 2022-11-06 16:56
import django
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, unique=True)),
                ("length", models.IntegerField()),
                ("expected_time", models.IntegerField()),
                ("ascent", models.IntegerField()),
                ('difficulty', models.CharField(max_length=100)),
                ("start_point_lat", models.FloatField()),
                ("start_point_lng", models.FloatField()),
                ("start_point_address", models.CharField(max_length=100)),
                ("end_point_lat", models.FloatField()),
                ("end_point_lng", models.FloatField()),
                ("end_point_address", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("track_file", models.FileField(upload_to="tracks")),
            ],
        ),
        migrations.CreateModel(
            name="HikeReferencePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_point_lan", models.FloatField()),
                ("reference_point_lng", models.FloatField()),
                ("reference_point_address", models.CharField(max_length=100)),
                (
                    "hike",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hiketracking.hike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="hikereferencepoint",
            constraint=models.UniqueConstraint(
                fields=("hike", "reference_point_lan", "reference_point_lng"),
                name="hikeref",
            ),
        ),
    ]
