# Generated by Django 4.1.3 on 2022-11-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiketracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
