# Generated by Django 4.1.2 on 2022-11-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiketracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hikereferencepoint',
            name='hikeref',
        ),
        migrations.RenameField(
            model_name='hike',
            old_name='end_point',
            new_name='end_point_address',
        ),
        migrations.RenameField(
            model_name='hike',
            old_name='start_point',
            new_name='start_point_address',
        ),
        migrations.RenameField(
            model_name='hikereferencepoint',
            old_name='reference_point',
            new_name='reference_point_address',
        ),
        migrations.AddField(
            model_name='hike',
            name='end_point_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hike',
            name='end_point_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hike',
            name='start_point_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hike',
            name='start_point_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hikereferencepoint',
            name='reference_point_lan',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hikereferencepoint',
            name='reference_point_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='hikereferencepoint',
            constraint=models.UniqueConstraint(fields=('hike', 'reference_point_lan', 'reference_point_lng'), name='hikeref'),
        ),
    ]
