# Generated by Django 4.1.3 on 2022-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiketracking', '0003_hike_local_guide'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hikereferencepoint',
            name='hikeref',
        ),
        migrations.RenameField(
            model_name='hikereferencepoint',
            old_name='reference_point_lan',
            new_name='reference_point_lat',
        ),
        migrations.AddConstraint(
            model_name='hikereferencepoint',
            constraint=models.UniqueConstraint(fields=('hike', 'reference_point_lat', 'reference_point_lng'), name='hikeref'),
        ),
    ]
