# Generated by Django 4.1.3 on 2022-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiketracking', '0004_remove_hikereferencepoint_hikeref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='province',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
